spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.110.112/blog?useUnicode=true&characterEncoding=UTF-8


  redis:
    host: localhost # Redis服务器地址
    database: 19 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:db/mybatis/*.xml
  type-aliases-package: com.springboot.blog.entity

logging:
  level:
    com.springboot.blog.mapper: debug
jwt:
  tokenHead: "Bearer "
