spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/blog?useUnicode=true&characterEncoding=UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:db/mybatis/*.xml
  type-aliases-package: com.springboot.blog.entity

logging:
  level:
    com.springboot.blog.mapper: debug

jwt:
  tokenHead: "Bearer "
